FROM registry.access.redhat.com/ubi8/ubi-minimal:latest
LABEL maintainer="William Caban <william.caban@redhat.com>"

ENV HISTORY_MAX=200
ENV HELM_HOST=":44134"
ENV KUBECONFIG="/kubeconfig"

# NOTE: Set this to the kubeconfig in KUBECONFIG
COPY  PATH_TO_KUBECONFIG  /kubeconfig

COPY ./linux-amd64/helm   /helm
COPY ./linux-amd64/tiller /tiller


EXPOSE 44134

USER nobody

ENTRYPOINT ["/tiller","--storage=secret -listen ${HELM_HOST} -alsologtostderr -history-max ${HISTORY_MAX}"]